### ISSUE TITLE
How to select the camera

### ISSUE THREAD

**Issue by balzercomp** [miyako/4d-plugin-capture-v2#1]
Hi Keysuke,

I see the command for the device list, but how can I select the camera for taking the picture or recording the movie?

Thanks

Gerald

**Comment by miyako** [comment]
is this macOS? if yes, you need to codesign and notarise your app with the necessary privacy manifest.

**Comment by miyako** [comment]
haven't tried, but looking at the source code, it seems like the command `capture Start` accepts an object in `$1` and the `device` property is the device ID.

**Comment by balzercomp** [comment]
I'll try it. I only saw that in the doc for the old plugin

**Comment by balzercomp** [comment]
It works. Thanks
